#!/bin/bash
set -x
export EXPDIR="${EXPDIR:-${HOMEglobal}/parm/config/${NET}}"
export WIPE_DATA="NO"
export DATAjob="${DATAROOT}/${RUN}_marineanalysis.${PDY:-}${cyc}"
export DATAens="${DATAjob}/ensdata"
export DATA="${DATAjob}/marineanlvar"
source "${HOMEglobal}/ush/jjob_header.sh"

# Source config files
for config in base marineanl marineanlchkpt; do
    source "${EXPDIR}/config.${config}" && true
    export err=$?
    if [[ ${err} -ne 0 ]]; then
        err_exit "[${BASH_SOURCE[0]}]: Unable to load config config.${config}"
    fi
done

# Source machine runtime environment
source "${HOMEglobal}/env/${machine}.env" "marineanlchkpt" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "[${BASH_SOURCE[0]}]: Error while sourcing machine environment ${machine}.env for job marineanlchkpt"
fi

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

##############################################
# Begin JOB SPECIFIC work
##############################################

###############################################################
# Run relevant script

EXSCRIPT=${GDASMARINEANALYSIS:-${SCRglobal}/exglobal_marine_analysis_checkpoint.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to update the ocean increment and/or ice restarts"
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

exit 0
