#! /usr/bin/env bash
set -x
export EXPDIR="${EXPDIR:-${HOMEglobal}/parm/config/${NET}}"
# shellcheck disable=SC2153  # PDY is always set in environment
source "${HOMEglobal}/ush/jjob_header.sh"

# Source config files
for config in base gen_control_ic; do
    source "${EXPDIR}/config.${config}" && true
    export err=$?
    if [[ ${err} -ne 0 ]]; then
        err_exit "[${BASH_SOURCE[0]}]: Unable to load config config.${config}"
    fi
done

# Source machine runtime environment
source "${HOMEglobal}/env/${machine}.env" "gen_control_ic" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "[${BASH_SOURCE[0]}]: Error while sourcing machine environment ${machine}.env for job gen_control_ic"
fi

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

# Initial conditions are from previous GFS cycle, but valid at the end of the cycle
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
# shellcheck disable=SC2155
BDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - $((assim_freq / 2)) hours")
export BDATE

# Define COM directories
# TODO: uncomment when testing for realtime
#COMINgfs=$(compath.py "${envir}/gfs/${gfs_ver}")
declare -rx COMOUT_ATMOS_INPUT_MEM="${ROTDIR}/${RUN}.${PDY}/${cyc}/mem000/model/atmos/input"
###############################################################
# Create COMOUT_ATMOS_INPUT_MEM
mkdir -p "${COMOUT_ATMOS_INPUT_MEM}"
###############################################################

# Define the input ATM_FILE and SFC_FILE from GFS
export ATM_FILE="${COMINgfs:-}/gfs.${GDATE:0:8}/${GDATE:8:2}/atmos/history/gfs.t${GDATE:8:2}.atm.f003.nc"
export SFC_FILE="${COMINgfs:-}/gfs.${GDATE:0:8}/${GDATE:8:2}/atmos/history/gfs.t${GDATE:8:2}.sfc.f003.nc"
###############################################################
# Run relevant script
${CHGRESFCSTSH:-${SCRglobal}/exglobal_atmos_chgres_gen_control.sh} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to run chgres_cube, ABORT!"
fi
##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
