#! /usr/bin/env bash
set -x
export EXPDIR="${EXPDIR:-${HOMEglobal}/parm/config/${NET}}"
export DATA=${DATA:-${DATAROOT}/${RUN}fetch_${cyc}}
source "${HOMEglobal}/ush/jjob_header.sh"

# Source config files
for config in base fetch; do
    source "${EXPDIR}/config.${config}" && true
    export err=$?
    if [[ ${err} -ne 0 ]]; then
        err_exit "[${BASH_SOURCE[0]}]: Unable to load config config.${config}"
    fi
done

# Source machine runtime environment
source "${HOMEglobal}/env/${machine}.env" "fetch" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "[${BASH_SOURCE[0]}]: Error while sourcing machine environment ${machine}.env for job fetch"
fi

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

# Execute fetching
# Do not export shell opts to the bash scripts in the htar/hsi wrappers
export -n SHELLOPTS
"${SCRglobal}/exglobal_fetch.py"
err=$?

###############################################################

exit "${err}"
